### PR TITLE
Fix crash on missing percent

### LINKED ISSUE #7: Handle exempt tax rates (percent == nil)
* Exempt rates with percent as nil are currently causing panics due to nil pointers.

### PR DESCRIPTION
**Pull request by cavalle**
* Fixes #7

### CODE REVIEW

File: items.go [hunk 1]
```diff
@@ -92,10 +92,12 @@ func (l *InvoiceLine) addTaxes(total num.Amount, taxes *tax.Total, rates tax.Set
 		tax := new(Tax)
 		tax.Code = categoryTaxCodeMap[ct.Code]
 		tax.Base = makeAmount(total)
-		if rate.Percent != nil {
-			tax.Rate = rate.Percent.StringWithoutSymbol()
-			tax.Amount = makeAmount(rate.Percent.Of(total))
+		percent := rate.Percent
+		if percent == nil {
+			percent = num.NewPercentage(0, 0)
```
Comment (samlown) [inline items.go:97]: Are you sure this is correct? In theory a zero rate is not the same as exempt...
